const TeamData24=[
    {
        name:"ANUBHAV RAWAT",
        post:"PRESIDENT, ECELL",
        imgURL:"https://t3.ftcdn.net/jpg/03/22/53/38/360_F_322533850_Lz5JL2K0nVqL48gjCiRLSa2ssxpdfyer.jpg",
        email:"aashihjoshilak@gmail.com",
        linkedIn:"https://www.linkedin.com/in/aashish-joshi-a72a71228/",
    },
    {
        name:"AASHISH JOSHI",
        post:"VICE-PRESIDENT, ECELL",
        imgURL:"src/assets/team/aashish2.png",
        email:"aashihjoshilak@gmail.com",
        linkedIn:"https://www.linkedin.com/in/aashish-joshi-a72a71228/",
    },
    {
        name:"JANHVI SEHGAL",
        post:"VICE-PRESIDENT, ECELL",
        imgURL:"https://t4.ftcdn.net/jpg/02/24/86/95/360_F_224869519_aRaeLneqALfPNBzg0xxMZXghtvBXkfIA.jpg",
        email:"aashihjoshilak@gmail.com",
        linkedIn:"https://www.linkedin.com/in/aashish-joshi-a72a71228/",
    }
    ,
    {
        name:"RAHUL SHEKHAWAT",
        post:"GENERAL SECRETARY, ECELL",
        imgURL:"https://t4.ftcdn.net/jpg/02/24/86/95/360_F_224869519_aRaeLneqALfPNBzg0xxMZXghtvBXkfIA.jpg",
        email:"aashihjoshilak@gmail.com",
        linkedIn:"https://www.linkedin.com/in/aashish-joshi-a72a71228/",
    },
    {
        name:"ADITYA",
        post:"EVENT MANAGER, ECELL",
        imgURL:"https://t4.ftcdn.net/jpg/02/24/86/95/360_F_224869519_aRaeLneqALfPNBzg0xxMZXghtvBXkfIA.jpg",
        email:"aashihjoshilak@gmail.com",
        linkedIn:"https://www.linkedin.com/in/aashish-joshi-a72a71228/",
    },
    {
        name:"SNEHA",
        post:"EVENT MANAGER, ECELL",
        imgURL:"https://t4.ftcdn.net/jpg/02/24/86/95/360_F_224869519_aRaeLneqALfPNBzg0xxMZXghtvBXkfIA.jpg",
        email:"aashihjoshilak@gmail.com",
        linkedIn:"https://www.linkedin.com/in/aashish-joshi-a72a71228/",
    },
    {
        name:"ADITYA KASHYAP",
        post:"TREASURER, ECELL",
        imgURL:"https://t4.ftcdn.net/jpg/02/24/86/95/360_F_224869519_aRaeLneqALfPNBzg0xxMZXghtvBXkfIA.jpg",
        email:"aashihjoshilak@gmail.com",
        linkedIn:"https://www.linkedin.com/in/aashish-joshi-a72a71228/",
    },
    {
        name:"DEEPANSHU",
        post:"PUBLIC RELATIONS, ECELL",
        imgURL:"https://t4.ftcdn.net/jpg/02/24/86/95/360_F_224869519_aRaeLneqALfPNBzg0xxMZXghtvBXkfIA.jpg",
        email:"aashihjoshilak@gmail.com",
        linkedIn:"https://www.linkedin.com/in/aashish-joshi-a72a71228/",
    },
    {
        name:"SIRAJUDDIN",
        post:"PUBLIC RELATIONS, ECELL",
        imgURL:"https://t4.ftcdn.net/jpg/02/24/86/95/360_F_224869519_aRaeLneqALfPNBzg0xxMZXghtvBXkfIA.jpg",
        email:"aashihjoshilak@gmail.com",
        linkedIn:"https://www.linkedin.com/in/aashish-joshi-a72a71228/",
    },
    {
        name:"ANUSHKA",
        post:"CORPORATE RELATIONS HEAD, ECELL",
        imgURL:"https://t4.ftcdn.net/jpg/02/24/86/95/360_F_224869519_aRaeLneqALfPNBzg0xxMZXghtvBXkfIA.jpg",
        email:"aashihjoshilak@gmail.com",
        linkedIn:"https://www.linkedin.com/in/aashish-joshi-a72a71228/",
    },
    {
        name:"PRIYANKA",
        post:"MEETINGS & BRAINSTORMING HEAD, ECELL",
        imgURL:"https://t4.ftcdn.net/jpg/02/24/86/95/360_F_224869519_aRaeLneqALfPNBzg0xxMZXghtvBXkfIA.jpg",
        email:"aashihjoshilak@gmail.com",
        linkedIn:"https://www.linkedin.com/in/aashish-joshi-a72a71228/",
    },
    {
        name:"GARIMA",
        post:"CONTENT & MEDIA HEAD, ECELL",
        imgURL:"https://t4.ftcdn.net/jpg/02/24/86/95/360_F_224869519_aRaeLneqALfPNBzg0xxMZXghtvBXkfIA.jpg",
        email:"aashihjoshilak@gmail.com",
        linkedIn:"https://www.linkedin.com/in/aashish-joshi-a72a71228/",
    },
    {
        name:"OJASWI KUMAR",
        post:"R&D HEAD, ECELL",
        imgURL:"https://t4.ftcdn.net/jpg/02/24/86/95/360_F_224869519_aRaeLneqALfPNBzg0xxMZXghtvBXkfIA.jpg",
        email:"aashihjoshilak@gmail.com",
        linkedIn:"https://www.linkedin.com/in/aashish-joshi-a72a71228/",
    },
    {
        name:"CHAVI YADAV",
        post:"MARKETING & OUTREACH HEAD, ECELL",
        imgURL:"https://t4.ftcdn.net/jpg/02/24/86/95/360_F_224869519_aRaeLneqALfPNBzg0xxMZXghtvBXkfIA.jpg",
        email:"aashihjoshilak@gmail.com",
        linkedIn:"https://www.linkedin.com/in/aashish-joshi-a72a71228/",
    },
    {
        name:"GARIMA SHARMA",
        post:"SPONSORSHIP HEAD, ECELL",
        imgURL:"https://t4.ftcdn.net/jpg/02/24/86/95/360_F_224869519_aRaeLneqALfPNBzg0xxMZXghtvBXkfIA.jpg",
        email:"canegib589@abatido.com",
        linkedIn:"https://www.linkedin.com/in/aashish-joshi-a72a71228/",
    },
]
export default TeamData24